# Generated by Django 2.2.5 on 2023-08-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('sex', models.CharField(max_length=10)),
                ('birthday', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': '用户测试表',
                'verbose_name_plural': '用户测试表',
                'db_table': 'tb_user_test',
                'unique_together': {('username', 'address')},
            },
        ),
    ]
