# Generated by Django 2.2.5 on 2023-08-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='birthday',
            field=models.DateField(verbose_name='出生日期'),
        ),
    ]
