# Generated by Django 2.2.5 on 2024-03-07 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=13, verbose_name='姓名')),
                ('addr', models.CharField(max_length=20, verbose_name='地址')),
            ],
            options={
                'verbose_name': '图书',
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('gender', models.BooleanField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.test')),
            ],
            options={
                'verbose_name': '人物信息',
                'db_table': 'test2',
            },
        ),
    ]
