# Generated by Django 2.2.5 on 2024-03-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='员工姓名')),
                ('age', models.IntegerField(max_length=20, verbose_name='员工年龄')),
                ('dep_name', models.CharField(max_length=30, verbose_name='部门名称')),
                ('dep_location', models.CharField(max_length=30, verbose_name='部门位置')),
            ],
            options={
                'verbose_name': '员工信息',
                'db_table': 'emp',
            },
        ),
    ]
