# Generated by Django 2.2.5 on 2024-03-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='age',
            field=models.IntegerField(verbose_name='员工年龄'),
        ),
    ]
