# Generated by Django 2.2.5 on 2024-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20240310_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=20, verbose_name='部门名称')),
                ('dep_location', models.CharField(max_length=20, verbose_name='部门名称')),
            ],
            options={
                'verbose_name': '部门',
                'db_table': 'department',
            },
        ),
    ]
