# Generated by Django 2.2.5 on 2024-03-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('dep_id', models.IntegerField(verbose_name='部门id')),
            ],
            options={
                'verbose_name': '员工',
                'db_table': '员工',
            },
        ),
    ]
