# Generated by Django 2.2.5 on 2024-03-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_employee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
